from .least_confidence import LeastConfidence
from .margin_sampling import MarginSampling
from .entropy_sampling import EntropySampling
from .kmeans_sampling import KMeansSampling
from .bayesian_active_learning_disagreement_dropout import BALDDropout
from .kcenter_greedy_pca import KCenterGreedyPCA
from .var_ratio import VarRatio
from .mean_std import MeanSTD
from .badge_sampling import BadgeSampling